# Generated by Django 3.1.3 on 2020-11-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mandal', '0001_initial'),
        ('PHC', '__first__'),
        ('village_sec', '__first__'),
        ('village', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pkid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('adhaar', models.CharField(blank=True, max_length=256)),
                ('relation', models.CharField(max_length=30)),
                ('gaurdian_name', models.CharField(max_length=50)),
                ('age', models.SmallIntegerField(default=0)),
                ('gender', models.CharField(default='NaN', max_length=3)),
                ('address', models.CharField(max_length=500)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('bloodgroup', models.CharField(default=None, max_length=4)),
                ('PVTG', models.CharField(default=None, max_length=5)),
                ('maritalstatus', models.CharField(default=None, max_length=15, null=True)),
                ('BasicVitals', models.JSONField(null=True)),
                ('BasicSymptoms', models.JSONField(null=True)),
                ('report', models.JSONField(null=True)),
                ('habits', models.JSONField(null=True)),
                ('pedalEdema', models.CharField(blank=True, max_length=2)),
                ('pedal_profile', models.JSONField(null=True)),
                ('KidneyProfile', models.JSONField(null=True)),
                ('doctorreq', models.BooleanField(default=False)),
                ('hospitalAdmit', models.CharField(blank=True, max_length=50)),
                ('opd', models.BooleanField(default=False)),
                ('dateOfAdmit', models.CharField(blank=True, max_length=10)),
                ('refered', models.BooleanField(default=False)),
                ('referredto', models.CharField(blank=True, max_length=50)),
                ('ref_status', models.TextField(blank=True, max_length=300)),
                ('treatmentDone', models.TextField(blank=True, max_length=300)),
                ('DischargeDetails', models.JSONField(null=True)),
                ('deceased', models.BooleanField(default=False)),
                ('DetailsDeath', models.JSONField(null=True)),
                ('AnemiaProfile', models.JSONField(null=True)),
                ('type_data', models.CharField(blank=True, max_length=50, null=True)),
                ('mandal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mandal.mandal')),
                ('phc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PHC.phc')),
                ('village', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='village.village')),
                ('villagesec', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='village_sec.village_sec')),
            ],
        ),
    ]
