# Generated by Django 3.1.3 on 2020-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20201116_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='PatientHealthStatus',
            field=models.JSONField(null=True),
        ),
    ]
