# Generated by Django 3.1.3 on 2020-11-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_patienthealthstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
