# Generated by Django 3.1.3 on 2020-11-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_mobile', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
